# Generated by Django 4.1.4 on 2023-02-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools_site', '0001_initial'),
        ('users', '0003_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools_site.schools'),
        ),
    ]
